### ISSUE TITLE
Code review comments

### ISSUE THREAD

**Issue by parthpp** [elasticpath/lex-chatbot#5]
Hi @KurtisLawson and @shaunmaharaj 
Following are some of the issues I found while reviewing the codebase for lex bot
1. Database region is hardcoded in [dynamo cache](https://github.com/elasticpath/lex-chatbot/blob/master/ep-lambda-function/dynamoCache.js#L2). I think we should have accept an enviornment variable here so as to give user the flexibility of deploying in different regions
2. Why do we have [lex-model.json](https://github.com/elasticpath/lex-chatbot/blob/master/ep-lex-models/lex-model.json)? Is it so that the user do not need to manually set all the intents in lex console, which they would have to do if they use [lex-model_blank.json](https://github.com/elasticpath/lex-chatbot/blob/master/ep-lex-models/lex-model_blank.json). The issue I see with this is that the [ARN syntax](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arn-syntax-lambda) for lambda's have account id. Hence, even if users want to use [lex-model.json](https://github.com/elasticpath/lex-chatbot/blob/master/ep-lex-models/lex-model.json), they would have to modify the codehooks according to their ARN's throughout the [lex-model.json](https://github.com/elasticpath/lex-chatbot/blob/master/ep-lex-models/lex-model.json). We should somehow make it easier to make the ARN change. This should also be documented somewhere.
3. We do have `ask-sdk-core` and `ask-sdk-model` dependencies in [`package.json`](https://github.com/elasticpath/lex-chatbot/blob/master/ep-lambda-function/package.json#L9-L10) but could not find any usage of these modules. How are we consuming these modules? If not needed we should remove it.
4. How are we using [en-US.json](https://github.com/elasticpath/lex-chatbot/blob/master/ep-lambda-function/models/en-US.json)? If not needed we should remove it. The same applied for [auth.interceptor.js](https://github.com/elasticpath/lex-chatbot/blob/master/ep-lambda-function/interceptors/auth.interceptor.js)
4. What is the purpose of [updateLambda.sh](https://github.com/elasticpath/lex-chatbot/blob/master/ep-lambda-function/updateLambda.sh) file? If it is meant to be run by the user then we should document it.
5. The reply messages are hardcoded in the lambda functions. Is it possible to move these message templates to a single place and just inject it in the required lambda accordingly?

**Comment by shaunmaharaj** [comment]
Addressed in latest commits from @KurtisLawson
